### ISSUE TITLE
File /etc/hostsctl.conf not created on install

### ISSUE THREAD

**Issue by adambro** [levisabah/hostsctl#21]
Today I've installed from AUR, but `/etc/hostsctl.conf` was not present. I see that `install.sh` has got the `cp` instruction commented out. Is that intentional?

**Comment by 0xl3vi** [comment]
Hi @adambro if we will ship `hostsctl.conf` with the default installation,
it will override `remote_hosts` with empty string.

the default `remote_hosts` is hardcoded in the script.
maybe in the  future we will move this to `hostsctl.conf`

**Comment by adambro** [comment]
OK, but think about the defaults please. Just after install twitter.com and facebook.com did not worked, because both were on blocked list. I've reverted the defaults pretty quickly to some conservative list.

**Comment by 0xl3vi** [comment]
Hi @adambro, I think we need to create `wizard` function in `install.sh`,
for selecting the default `hosts` file.
you can create a pull request if you want. :+1:
