### ISSUE TITLE
0.0.0.0 broadcasthost in /etc/hosts

### ISSUE THREAD

**Issue by md-clone** [levisabah/hostsctl#28]
Hi, the latest update put all the lines other than 0.0.0.0 in /etc/hosts to 0.0.0.0 like this one for example:
"255.255.255.255 broadcasthost" gives "0.0.0.0 broadcasthost"

I replaced it manually.

**Comment by levisabah** [comment]
@md-clone thanks for reporting this :+1: .
fixed.
