### ISSUE TITLE
Duplicate active and inactive entries

### ISSUE THREAD

**Issue by pigmonkey** [levisabah/hostsctl#4]
I'm using [Steven Black's default hosts](https://github.com/StevenBlack/hosts/blob/master/hosts).

The domain `ssl.google-analytics.com` appears in both the active and inactive lists.

    $ hostsctl list-active | grep -i ssl.google-analytics.com
    ● ssl.google-analytics.com
    $ hostsctl list-inactive | grep -i ssl.google-analytics.com
    ● ssl.google-analytics.com

This is because line 18501 of the hosts file blocks the domain:

    0.0.0.0 ssl.google-analytics.com

But line 25600 includes the domain commented out as part of the spyware section:

    #<spyware-sites>
    # Spyware and user tracking
    # By entering domains here, it will prevent certain companies from
    # gathering information on your surfing habits. These servers do not
    # necessarily serve ads, instead some are used by certain products to
    # "phone home". Others use web cookies to gather statistics on surfing
    # habits. Among other uses, this is a common tactic by spammers, to
    # let them know that you have read your mail.
    # Uncomment (remove the #) the lines that you wish to block, as some
    # may provide you with services you like.

    #<maybe-spy>
    ...
    #0.0.0.0 ssl.google-analytics.com

I wonder if we need to change `hosts_list_active` to not just look for commented out hosts, but also diff it against what was found by `hosts_list_inactive` to catch these kinds of duplicate entries.

**Comment by 0xl3vi** [comment]
@pigmonkey good point! thank you.
What If we will remove any duplicate in the file when calling `hosts_update` ?

**Comment by pigmonkey** [comment]
That would solve the problem.

The only downside I see is that it would prevent the user from cleanly diffing their current hosts against the latest version. Right now, if it has been a while since I've updated, I could manually download the latest version of whatever source I'm using and compare it against my current `/etc/hosts` to see what has changed.

I'm not sure if there is much realistic value in that ability, and since we'd only be removing lines that are already commented out it probably doesn't matter.

**Comment by pigmonkey** [comment]
This should probably be reopened until we find a better fix for `hosts_export()`.

A band-aid would be to use grep to strip out all comments.

    $ cat /etc/hostsctl.d/* | grep -v '^#'

That would solve the exact problem I specified initially, but it would not prevent the remote hosts file from overwriting a host that the user has enabled (ie, commented out in 20-enabled-disabled).

**Comment by 0xl3vi** [comment]
I will try to work on this today, if I will have time :smirk:

**Comment by pigmonkey** [comment]
I think this might be easier to solve if we split the enabled and disabled hosts into different files.

Store enabled hosts in `20-enabled` as domains only, ie:

    facebook.com
    analytics.google.com

Store disabled hosts in `21-disabled` or someplace as normal host entries:

    0.0.0.0 click.buzzcity.net
    0.0.0.0 ad.where.com

Remove all lines in the remote hosts file that are empty white space, or start with a comment, or match an entry in `20-enabled`.

    grep -v -e '^\s*$' -e '^#' -e ' facebook.com' -e ' analytics.google.com' /etc/hostsctl.d/30-remote

Finally, concatenate that grep output with the content of every other file in `/etc/hostsctl.d/` except for `20-enabled` and `30-remote`. Pipe that through `uniq` and `sort` for the final dedupe.

Anything the user has enabled is simply not in the final output, so we don't have to worry about treating comments carefully, or them being accidentally overwritten by non-commented but otherwise identical lines later on. Anything the user has disabled is handled normally, but gets entered before the cleaned output of the remote hosts files, so that the user's entries have precedence.

**Comment by 0xl3vi** [comment]
@pigmonkey I also thought on this.

but I have better solution using "SQLite" database for the hosts.
something like "/etc/hostsctl.d/hosts.db" and we can mange the hosts easily.

all the default /etc/hostsctl.d/ files will be kept.

```awk
=> /etc/hostsctl.d/* -------> host exists ? / host enabled? |
                                                <------------------------------------
                                       SKIP  | INSERT TO SQLITE_DB (enable/disable/new/remove) 
                                                |
                                         /etc/hosts
```

```sql
SELECT * FROM `hosts` WHERE hostname LIKE "facebook.com"
INSERT INTO hosts(status) VALUES("disabled") WHERE hostname LIKE "twitter.com"
```

almost all the flavours of Linux and Android/Mac are being shipped with "SQLite"
And we can add more features with a database.
